<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId></PackageId>
        <Version></Version>
        <Authors></Authors>
        <Company></Company>
        <Description></Description>
        <RepositoryUrl></RepositoryUrl>
        <PackageTags></PackageTags>
        <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
        <Title></Title>
        <PackageProjectUrl></PackageProjectUrl>
        <PackageIcon></PackageIcon>
        <SignAssembly>False</SignAssembly>
        <LangVersion>12</LangVersion>
        <PackageReleaseNotes></PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <IsPublishable>True</IsPublishable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <IsPublishable>True</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="jose-jwt" Version="5.2.0" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.5" />
      <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="9.0.5" />
      <PackageReference Include="Microsoft.Identity.Client" Version="4.72.1" />
      <PackageReference Include="RedLock.net" Version="2.3.2" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
      <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
